# -*- coding: utf-8 -*-
"""MallaCurricular2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13bajShpCw3u1G8_GqYdltVEtLTfiEgDV
"""

!git clone https://github.com/jcorrean/LAND.git

# -*- coding: utf-8 -*-
"""
visualizador_malla_curricular_v2.py
"""
!pip install pyvis

import json
from pyvis.network import Network
import pandas as pd

# ==========================================
# 1. LEER ARCHIVO DE ARISTAS Y PREPARAR DATOS
# ==========================================

df = pd.read_csv("/content/LAND/Lista_de_aristas.csv", sep=',', encoding='utf8')

competencia_funcion = (
    df[["Competencia_ID", "Funciones"]]
    .drop_duplicates()
    .set_index("Competencia_ID")["Funciones"]
    .to_dict()
)

semestre_por_asignatura = (
    df[['Asignatura', 'Semestre']]
    .drop_duplicates()
    .set_index('Asignatura')['Semestre']
    .to_dict()
)

# ==========================================
# 2. DEFINICIÓN DE FUNCIONES
# ==========================================

funciones = {
    "1": "Modelos de negocio y emprendimiento digital",
    "2": "Analítica de datos y humanización del dato",
    "3": "Toma de decisiones y resolución de problemas",
    "4": "Liderazgo humanista y transformación digital",
    "5": "Transformación y sostenibilidad organizacional"
}

# ==========================================
# 3. DESCRIPCIONES DE COMPETENCIAS
# ==========================================

descripciones = {
    "Competencia 1.1": "Entiende y aprovecha las formas de interacción entre la empresa, clientes, proveedores para la supervivencia del negocio",
    "Competencia 1.2": "Propone nuevos modelos de negocio para aprovechar sus ventajas y apoya a la alta dirección para estos nuevos modelos de negocio.",
    "Competencia 1.3": "Propone e implementa estrategias de emprendimiento generar valor económico y social con metodologías de innovación y tecnologías de vanguardia.",
    "Competencia 2.1": "Procesa grandes volúmenes de datos mediante software estadístico y lenguajes de programación.",
    "Competencia 2.2": "Identifica patrones, correlaciones y tendencias para la toma de decisiones estratégicas.",
    "Competencia 2.3": "Diseña estrategias de intervención sustentadas en datos para optimizar procesos organizacionales.",
    "Competencia 3.1": "Desarrolla KPI e informes mediante integración de datos comerciales, financieros y operativos.",
    "Competencia 3.2": "Resuelve problemas complejos utilizando pensamiento sistémico y evidencia.",
    "Competencia 3.3": "Aplica criterios éticos en la gestión y análisis de datos.",
    "Competencia 4.1": "Identifica sesgos algorítmicos y riesgos de exclusión o discriminación.",
    "Competencia 4.2": "Evalúa críticamente la calidad de los datos para proponer soluciones innovadoras.",
    "Competencia 4.3": "Lidera proyectos tecnológicos considerando impactos ambientales, sociales y de negocio.",
    "Competencia 5.1": "Diseña estrategias de transformación digital con atención a impactos ambientales y sociales.",
    "Competencia 5.2": "Asesora a la alta dirección mediante comunicación efectiva basada en evidencia.",
    "Competencia 5.3": "Aplica modelos de gestión de riesgos y continuidad de negocio."
}

# ==========================================
# 4. COLORES POR FUNCIÓN
# ==========================================

colores_funcion = {
    "Propone modelos de negocio y emprendimiento": "#1f77b4",
    "Analiza volúmenes masivos de datos para generar conocimiento util": "#2ca02c",
    "Diseña propuestas y estrategias para apoyar la toma de decisiones": "#ff7f0e",
    "Ejerce liderazgo humanista en la transformación digital": "#9467bd",
    "Formula recomendaciones y planes para la transformación digital y asegurar su sostenibilidad": "#d62728"
}

def obtener_color_funcion(fn_nombre):
    if fn_nombre in colores_funcion:
        return colores_funcion[fn_nombre]
    for k, v in colores_funcion.items():
        if k.lower() in str(fn_nombre).lower() or str(fn_nombre).lower() in k.lower():
            return v
    return "#FFFFFF"

# ==========================================
# 5. INICIALIZAR RED PYVIS (ALTURA AJUSTADA AL 100vh)
# ==========================================

net = Network(
    height="100vh",
    width="100%",
    bgcolor="#222222",
    font_color="white",
    notebook=False
)

# ==========================================
# 6. AGREGAR NODOS CON TAMAÑO PROPORCIONAL A CENTRALIDAD DE GRADO
# ==========================================

asignaturas = sorted(df["Asignatura"].unique())
for asignatura in asignaturas:
    grado = len(df[df["Asignatura"] == asignatura])
    net.add_node(
        asignatura,
        label=asignatura,
        color="#FFFFFF",
        tipo="asignatura",
        semestre=str(semestre_por_asignatura[asignatura]),
        shape="dot",
        size=12 + (grado * 3),
        title=f"""<b>Asignatura</b><br>{asignatura}<br><br><b>Semestre</b><br>{semestre_por_asignatura[asignatura]}<br><br>Centralidad de Grado (Competencias asociadas): {grado}"""
    )

competencias = sorted(df["Competencia_ID"].unique())
for comp in competencias:
    grado = len(df[df["Competencia_ID"] == comp])
    funcion = competencia_funcion[comp]
    desc = descripciones.get(comp, "")
    color = obtener_color_funcion(funcion)

    tooltip = f"""<b>{comp}</b><br><br><b>Función</b><br>{funcion}<br><br><b>Descripción</b><br>{desc}<br><br>Centralidad de Grado (Asignaturas conectadas): {grado}"""

    net.add_node(
        comp,
        label=comp.replace("Competencia ", ""),
        shape="diamond",
        color=color,
        size=15 + (grado * 3),
        funcion=funcion,
        tipo="competencia",
        title=tooltip
    )

# ==========================================
# 7. AGREGAR ARISTAS MODO 1 (ASIGNATURA ↔ COMPETENCIA)
# ==========================================

for idx, row in df.iterrows():
    net.add_edge(
        row["Asignatura"],
        row["Competencia_ID"],
        id=f"e_m1_{idx}",
        color="#999999",
        width=1.5,
        modo="mode1"
    )

# ==========================================
# 8. CALCULAR Y AGREGAR ARISTAS MODO 2 (PROYECCIÓN ASIGNATURA ↔ ASIGNATURA)
# ==========================================

asig_comp = df.groupby("Asignatura")["Competencia_ID"].apply(set).to_dict()

edge_m2_count = 0
for i in range(len(asignaturas)):
    for j in range(i + 1, len(asignaturas)):
        a1 = asignaturas[i]
        a2 = asignaturas[j]

        shared = sorted(list(asig_comp[a1].intersection(asig_comp[a2])))

        if len(shared) >= 2:
            list_items = "".join([f"• {c}<br>" for c in shared])
            edge_title = f"<b>Competencias compartidas:</b><br><br>{list_items}"

            edge_m2_count += 1
            net.add_edge(
                a1,
                a2,
                id=f"e_m2_{edge_m2_count}",
                color="#FFC107",
                width=1.0 + len(shared),
                title=edge_title,
                hidden=True,
                modo="mode2"
            )

# ==========================================
# 9. OPCIONES VISUALES
# ==========================================

net.set_options("""
{
  "interaction": {
    "hover": true,
    "tooltipDelay": 200,
    "navigationButtons": true,
    "dragNodes": true,
    "multiselect": true,
    "zoomView": true
  },
  "physics": {
    "barnesHut": {
      "gravitationalConstant": -30000,
      "centralGravity": 0.15,
      "springLength": 180,
      "springConstant": 0.04
    },
    "stabilization": {
      "iterations": 200
    }
  },
  "nodes": {
     "font": {
        "size": 14,
        "color": "white"
     }
  }
}
""")

# ==========================================
# 10. GUARDAR HTML BASE
# ==========================================

output_file = "grafo_competencias.html"
net.save_graph(output_file)

# ==========================================
# 11. PREPARAR DATOS PARA ESTRUCTURA JAVASCRIPT
# ==========================================

curriculum_data = []
for _, row in df.iterrows():
    curriculum_data.append({
        "asignatura": row["Asignatura"],
        "funcion": row["Funciones"],
        "competencia": row["Competencia_ID"],
        "semestre": str(row["Semestre"])
    })

curriculum_json = json.dumps(curriculum_data, ensure_ascii=False)

funciones_unicas = sorted(df["Funciones"].unique())
competencias_unicas = sorted(df["Competencia_ID"].unique())
asignaturas_unicas = sorted(df["Asignatura"].unique())

# ==========================================
# 12. CONSTRUIR PANEL IZQUIERDO, LEYENDA Y PIE DE PÁGINA HTML
# ==========================================

selector_html = """
<div id="panel" style="
position:absolute;
top:20px;
left:20px;
width:360px;
background:rgba(0,0,0,0.92);
padding:20px;
border-radius:10px;
border:1px solid gray;
color:white;
z-index:999;
font-family:Arial;
font-size:12px;
">

<h2>Explorador Curricular</h2>

<label><b>Modo de Visualización</b></label><br>
<select id="modeSelector" style="width:100%; background:#333; color:white; padding:5px; margin-bottom:15px; border:1px solid #555;" onchange="applyFilters()">
    <option value="mode1">Modo 1: Asignatura ↔ Competencia</option>
    <option value="mode2">Modo 2: Asignatura ↔ Asignatura (≥ 2 comp. compartidas)</option>
</select>

<br>

<label><b>Asignatura</b></label><br>
<select id="asignaturaFilter" style="width:100%;" onchange="applyFilters()">
<option value="ALL">Todas</option>
"""

for a in asignaturas_unicas:
    selector_html += f'<option value="{a}">{a}</option>\n'

selector_html += """
</select>

<br><br>

<label><b>Función</b></label><br>
<select id="funcionFilter" style="width:100%;" onchange="applyFilters()">
<option value="ALL">Todas</option>
"""

for f in funciones_unicas:
    selector_html += f'<option value="{f}">{f}</option>\n'

selector_html += """
</select>

<br><br>

<label><b>Competencia</b></label><br>
<select id="competenciaFilter" style="width:100%;" onchange="applyFilters()">
<option value="ALL">Todas</option>
"""

for c in competencias_unicas:
    selector_html += f'<option value="{c}">{c}</option>\n'

selector_html += """
</select>

<br><br>

<label><b>Semestre</b></label><br>
<select id="semestreFilter" style="width:100%;" onchange="applyFilters()">
<option value="ALL">Todos</option>
<option value="1">Semestre I</option>
<option value="2">Semestre II</option>
<option value="3">Semestre III</option>
<option value="4">Semestre IV</option>
<option value="5">Semestre V</option>
<option value="6">Semestre VI</option>
<option value="7">Semestre VII</option>
<option value="8">Semestre VIII</option>
</select>

<br><br>

<button onclick="resetGraph()" style="width:100%; padding:8px; cursor:pointer;">
Mostrar Red Completa
</button>

</div>
"""

# Leyenda derecha extendida
legend_items_html = ""
for fn in funciones_unicas:
    col = obtener_color_funcion(fn)
    comps_de_fn = sorted(df[df["Funciones"] == fn]["Competencia_ID"].unique())

    legend_items_html += f"""
    <div style="margin-bottom: 12px;">
        <div style="display:flex; align-items:center; margin-bottom:4px;">
            <span style="display:inline-block; width:14px; height:14px; background-color:{col}; margin-right:8px; border-radius:3px; flex-shrink:0;"></span>
            <strong style="color:white; font-size:12px;">{fn}</strong>
        </div>
        <ul style="margin: 4px 0 0 22px; padding:0; color:#ccc; font-size:11px; line-height:1.4;">
    """
    for c in comps_de_fn:
        desc_c = descripciones.get(c, "")
        legend_items_html += f"<li><b>{c}:</b> {desc_c}</li>"

    legend_items_html += "</ul></div>"

legend_html = f"""
<div id="legend" style="
position:absolute;
top:20px;
right:20px;
width:380px;
max-height:80vh;
overflow-y:auto;
background:rgba(0,0,0,0.92);
padding:20px;
border-radius:10px;
border:1px solid gray;
color:white;
z-index:999;
font-family:Arial;
font-size:12px;
">

<h2 style="margin-top:0;">Funciones y Competencias</h2>

<p style="color:#aaa; margin-bottom:15px;">
Agrupación funcional de competencias y sus descripciones asociadas:
</p>

<hr style="border: 0.5px solid #444; margin-bottom:15px;">

{legend_items_html}

</div>
"""

# Pie de página fijo y destacado en la parte inferior
footer_html = """
<div id="footer-banner" style="
position:fixed;
bottom:0;
left:0;
width:100%;
background:rgba(0, 0, 0, 0.95);
color:#ffffff;
text-align:center;
padding:10px 0;
font-family:Arial, sans-serif;
font-size:12px;
font-weight:bold;
border-top:1px solid #444;
z-index:10000;
box-shadow: 0px -2px 10px rgba(0,0,0,0.8);
">
Derechos Reservados Juan C. Correa, Departamento de Estudios Empresariales, Universidad Iberoamericana, Ciudad de México, 2026
</div>
"""

# Estilo para asegurar que el canvas de PyVis ocupe la pantalla completa sin ocultar el footer
custom_css = """
<style>
body, html {
    margin: 0;
    padding: 0;
    overflow: hidden;
    height: 100%;
    background-color: #222222;
}
#mynetwork {
    height: calc(100vh - 40px) !important;
}
</style>
"""

# ==========================================
# 13. INYECTAR LÓGICA JAVASCRIPT Y ENSAMBLAR HTML
# ==========================================

js_code = f"""
<script>
var curriculumData = {curriculum_json};

function resetGraph(){{
    document.getElementById("modeSelector").value = "mode1";
    document.getElementById("asignaturaFilter").value = "ALL";
    document.getElementById("funcionFilter").value = "ALL";
    document.getElementById("competenciaFilter").value = "ALL";
    document.getElementById("semestreFilter").value = "ALL";
    applyFilters();
}}

function applyFilters(){{
    let mode = document.getElementById("modeSelector").value;
    let asignatura = document.getElementById("asignaturaFilter").value;
    let funcion = document.getElementById("funcionFilter").value;
    let competencia = document.getElementById("competenciaFilter").value;
    let semestre = document.getElementById("semestreFilter").value;

    let validRows = curriculumData.filter(function(row){{
        if(asignatura !== "ALL" && row.asignatura !== asignatura) return false;
        if(funcion !== "ALL" && row.funcion !== funcion) return false;
        if(competencia !== "ALL" && row.competencia !== competencia) return false;
        if(semestre !== "ALL" && row.semestre !== semestre) return false;
        return true;
    }});

    let activeAsignaturas = new Set();
    let activeCompetencias = new Set();

    validRows.forEach(function(row){{
        activeAsignaturas.add(row.asignatura);
        activeCompetencias.add(row.competencia);
    }});

    if(mode === "mode1"){{
        nodes.forEach(function(node){{
            let isVisible = false;
            if(node.tipo === "asignatura" && activeAsignaturas.has(node.id)){{
                isVisible = true;
            }} else if(node.tipo === "competencia" && activeCompetencias.has(node.id)){{
                isVisible = true;
            }}
            nodes.update({{ id: node.id, hidden: !isVisible }});
        }});

        edges.forEach(function(edge){{
            if(edge.modo === "mode1"){{
                let isVisible = activeAsignaturas.has(edge.from) && activeCompetencias.has(edge.to);
                edges.update({{ id: edge.id, hidden: !isVisible }});
            }} else {{
                edges.update({{ id: edge.id, hidden: true }});
            }}
        }});

    }} else if(mode === "mode2"){{
        nodes.forEach(function(node){{
            let isVisible = (node.tipo === "asignatura" && activeAsignaturas.has(node.id));
            nodes.update({{ id: node.id, hidden: !isVisible }});
        }});

        edges.forEach(function(edge){{
            if(edge.modo === "mode2"){{
                let isVisible = activeAsignaturas.has(edge.from) && activeAsignaturas.has(edge.to);
                edges.update({{ id: edge.id, hidden: !isVisible }});
            }} else {{
                edges.update({{ id: edge.id, hidden: true }});
            }}
        }});
    }}

    network.fit({{ animation: true }});
}}

// Ejecución inicial para aplicar estado tras renderizado del grafo
setTimeout(function(){{
    applyFilters();
}}, 500);
</script>
"""

with open(output_file, "r", encoding="utf-8") as f:
    html = f.read()

html = html.replace("<head>", f"<head>{custom_css}")
html = html.replace("<body>", f"<body>{selector_html}{legend_html}{footer_html}")
html = html.replace("</body>", js_code + "</body>")

with open(output_file, "w", encoding="utf-8") as f:
    f.write(html)

print("Visualizador v2 generado correctamente con pie de página fijo.")

# -*- coding: utf-8 -*-
"""
visualizador_malla_curricular_v2.py
"""

import json
import pandas as pd
from pyvis.network import Network

# ==========================================
# 1. LEER ARCHIVO DE ARISTAS Y PREPARAR DATOS
# ==========================================

df = pd.read_csv("/content/LAND/Lista_de_aristas.csv", sep=',', encoding='utf8')

competencia_funcion = (
    df[["Competencia_ID", "Funciones"]]
    .drop_duplicates()
    .set_index("Competencia_ID")["Funciones"]
    .to_dict()
)

semestre_por_asignatura = (
    df[['Asignatura', 'Semestre']]
    .drop_duplicates()
    .set_index('Asignatura')['Semestre']
    .to_dict()
)

# ==========================================
# 2. DEFINICIÓN DE FUNCIONES
# ==========================================

funciones = {
    "1": "Modelos de negocio y emprendimiento digital",
    "2": "Analítica de datos y humanización del dato",
    "3": "Toma de decisiones y resolución de problemas",
    "4": "Liderazgo humanista y transformación digital",
    "5": "Transformación y sostenibilidad organizacional"
}

# ==========================================
# 3. DESCRIPCIONES DE COMPETENCIAS
# ==========================================

descripciones = {
    "Competencia 1.1": "Propone modelos de negocio y emprendimiento en sectores digitales para capitalizar oportunidades estratégicas.",
    "Competencia 1.2": "Propone nuevos modelos de negocio y apoya a la alta dirección en la toma de decisiones.",
    "Competencia 1.3": "Implementa estrategias de emprendimiento digital para generar valor económico y social.",
    "Competencia 2.1": "Procesa grandes volúmenes de datos mediante software estadístico y lenguajes de programación.",
    "Competencia 2.2": "Identifica patrones, correlaciones y tendencias para la toma de decisiones estratégicas.",
    "Competencia 2.3": "Diseña estrategias de intervención sustentadas en datos para optimizar procesos organizacionales.",
    "Competencia 3.1": "Desarrolla KPI e informes mediante integración de datos comerciales, financieros y operativos.",
    "Competencia 3.2": "Resuelve problemas complejos utilizando pensamiento sistémico y evidencia.",
    "Competencia 3.3": "Aplica criterios éticos en la gestión y análisis de datos.",
    "Competencia 4.1": "Identifica sesgos algorítmicos y riesgos de exclusión o discriminación.",
    "Competencia 4.2": "Evalúa críticamente la calidad de los datos para proponer soluciones innovadoras.",
    "Competencia 4.3": "Lidera proyectos tecnológicos considerando impactos ambientales, sociales y de negocio.",
    "Competencia 5.1": "Diseña estrategias de transformación digital con atención a impactos ambientales y sociales.",
    "Competencia 5.2": "Asesora a la alta dirección mediante comunicación efectiva basada en evidencia.",
    "Competencia 5.3": "Aplica modelos de gestión de riesgos y continuidad de negocio."
}

# ==========================================
# 4. COLORES POR FUNCIÓN
# ==========================================

colores_funcion = {
    "Propone modelos de negocio y emprendimiento": "#1f77b4",
    "Analiza volúmenes masivos de datos para generar conocimiento util": "#2ca02c",
    "Diseña propuestas y estrategias para apoyar la toma de decisiones": "#ff7f0e",
    "Ejerce liderazgo humanista en la transformación digital": "#9467bd",
    "Formula recomendaciones y planes para la transformación digital y asegurar su sostenibilidad": "#d62728"
}

# ==========================================
# 5. INICIALIZAR RED PYVIS
# ==========================================

net = Network(
    height="900px",
    width="100%",
    bgcolor="#222222",
    font_color="white",
    notebook=False
)

# ==========================================
# 6. AGREGAR NODOS (ASIGNATURAS Y COMPETENCIAS)
# ==========================================

asignaturas = sorted(df["Asignatura"].unique())
for asignatura in asignaturas:
    grado = len(df[df["Asignatura"] == asignatura])
    net.add_node(
        asignatura,
        label=asignatura,
        color="#4A90E2",
        tipo="asignatura",
        semestre=str(semestre_por_asignatura[asignatura]),
        shape="dot",
        size=15 + grado,
        title=f"""<b>Asignatura</b><br>{asignatura}<br><br><b>Semestre</b><br>{semestre_por_asignatura[asignatura]}<br><br>Competencias asociadas: {grado}"""
    )

competencias = sorted(df["Competencia_ID"].unique())
for comp in competencias:
    grado = len(df[df["Competencia_ID"] == comp])
    funcion = competencia_funcion[comp]
    desc = descripciones.get(comp, "")
    color = colores_funcion.get(funcion, "#cccccc")

    tooltip = f"""<b>{comp}</b><br><br><b>Función</b><br>{funcion}<br><br><b>Descripción</b><br>{desc}<br><br>Asignaturas conectadas: {grado}"""

    net.add_node(
        comp,
        label=comp.replace("Competencia ", ""),
        shape="diamond",
        color=color,
        size=18 + grado * 2,
        funcion=funcion,
        tipo="competencia",
        title=tooltip
    )

# ==========================================
# 7. AGREGAR ARISTAS MODO 1 (ASIGNATURA ↔ COMPETENCIA)
# ==========================================

for idx, row in df.iterrows():
    net.add_edge(
        row["Asignatura"],
        row["Competencia_ID"],
        id=f"e_m1_{idx}",
        color="#999999",
        width=1.5,
        modo="mode1"
    )

# ==========================================
# 8. CALCULAR Y AGREGAR ARISTAS MODO 2 (PROYECCIÓN ASIGNATURA ↔ ASIGNATURA)
# ==========================================

asig_comp = df.groupby("Asignatura")["Competencia_ID"].apply(set).to_dict()

edge_m2_count = 0
for i in range(len(asignaturas)):
    for j in range(i + 1, len(asignaturas)):
        a1 = asignaturas[i]
        a2 = asignaturas[j]

        shared = sorted(list(asig_comp[a1].intersection(asig_comp[a2])))

        if len(shared) >= 2:
            list_items = "".join([f"• {c}<br>" for c in shared])
            edge_title = f"<b>Competencias compartidas:</b><br><br>{list_items}"

            edge_m2_count += 1
            net.add_edge(
                a1,
                a2,
                id=f"e_m2_{edge_m2_count}",
                color="#FFC107",
                width=1.0 + len(shared),
                title=edge_title,
                hidden=True,
                modo="mode2"
            )

# ==========================================
# 9. OPCIONES VISUALES
# ==========================================

net.set_options("""
{
  "interaction": {
    "hover": true,
    "tooltipDelay": 200,
    "navigationButtons": true,
    "dragNodes": true,
    "multiselect": true,
    "zoomView": true
  },
  "physics": {
    "barnesHut": {
      "gravitationalConstant": -30000,
      "centralGravity": 0.15,
      "springLength": 180,
      "springConstant": 0.04
    },
    "stabilization": {
      "iterations": 200
    }
  },
  "nodes": {
     "font": {
        "size": 14,
        "color": "white"
     }
  }
}
""")

# ==========================================
# 10. GUARDAR HTML BASE
# ==========================================

output_file = "grafo_competencias.html"
net.save_graph(output_file)

# ==========================================
# 11. PREPARAR DATOS PARA ESTRUCTURA JAVASCRIPT
# ==========================================

curriculum_data = []
for _, row in df.iterrows():
    curriculum_data.append({
        "asignatura": row["Asignatura"],
        "funcion": row["Funciones"],
        "competencia": row["Competencia_ID"],
        "semestre": str(row["Semestre"])
    })

curriculum_json = json.dumps(curriculum_data, ensure_ascii=False)

funciones_unicas = sorted(df["Funciones"].unique())
competencias_unicas = sorted(df["Competencia_ID"].unique())
asignaturas_unicas = sorted(df["Asignatura"].unique())

# ==========================================
# 12. CONSTRUIR PANEL IZQUIERDO Y LEYENDA HTML
# ==========================================

selector_html = """
<div id="panel" style="
position:absolute;
top:20px;
left:20px;
width:360px;
background:rgba(0,0,0,0.92);
padding:20px;
border-radius:10px;
border:1px solid gray;
color:white;
z-index:999;
font-family:Arial;
font-size:12px;
">

<h2>Explorador Curricular</h2>

<label><b>Modo de Visualización</b></label><br>
<select id="modeSelector" style="width:100%; background:#333; color:white; padding:5px; margin-bottom:15px; border:1px solid #555;" onchange="applyFilters()">
    <option value="mode1">Modo 1: Asignatura ↔ Competencia</option>
    <option value="mode2">Modo 2: Asignatura ↔ Asignatura (≥ 2 comp. compartidas)</option>
</select>

<br>

<label><b>Asignatura</b></label><br>
<select id="asignaturaFilter" style="width:100%;" onchange="applyFilters()">
<option value="ALL">Todas</option>
"""

for a in asignaturas_unicas:
    selector_html += f'<option value="{a}">{a}</option>\n'

selector_html += """
</select>

<br><br>

<label><b>Función</b></label><br>
<select id="funcionFilter" style="width:100%;" onchange="applyFilters()">
<option value="ALL">Todas</option>
"""

for f in funciones_unicas:
    selector_html += f'<option value="{f}">{f}</option>\n'

selector_html += """
</select>

<br><br>

<label><b>Competencia</b></label><br>
<select id="competenciaFilter" style="width:100%;" onchange="applyFilters()">
<option value="ALL">Todas</option>
"""

for c in competencias_unicas:
    selector_html += f'<option value="{c}">{c}</option>\n'

selector_html += """
</select>

<br><br>

<label><b>Semestre</b></label><br>
<select id="semestreFilter" style="width:100%;" onchange="applyFilters()">
<option value="ALL">Todos</option>
<option value="1">Semestre I</option>
<option value="2">Semestre II</option>
<option value="3">Semestre III</option>
<option value="4">Semestre IV</option>
<option value="5">Semestre V</option>
<option value="6">Semestre VI</option>
<option value="7">Semestre VII</option>
<option value="8">Semestre VIII</option>
</select>

<br><br>

<button onclick="resetGraph()" style="width:100%; padding:8px; cursor:pointer;">
Mostrar Red Completa
</button>

</div>
"""

legend_html = """
<div id="legend" style="
position:absolute;
top:20px;
right:20px;
width:350px;
max-height:90%;
overflow-y:auto;
background:rgba(0,0,0,0.92);
padding:20px;
border-radius:10px;
border:1px solid gray;
color:white;
z-index:999;
font-family:Arial;
font-size:12px;
">

<h2>Funciones</h2>

<p>
Los colores representan agrupaciones funcionales de competencias.
</p>

<hr>

<p>
Use los filtros y el selector de modo para explorar relaciones curriculares directas o proyecciones entre asignaturas.
</p>

</div>
"""

# ==========================================
# 13. INYECTAR LÓGICA JAVASCRIPT Y ENSAMBLAR HTML
# ==========================================

js_code = f"""
<script>
var curriculumData = {curriculum_json};

function resetGraph(){{
    document.getElementById("modeSelector").value = "mode1";
    document.getElementById("asignaturaFilter").value = "ALL";
    document.getElementById("funcionFilter").value = "ALL";
    document.getElementById("competenciaFilter").value = "ALL";
    document.getElementById("semestreFilter").value = "ALL";
    applyFilters();
}}

function applyFilters(){{
    let mode = document.getElementById("modeSelector").value;
    let asignatura = document.getElementById("asignaturaFilter").value;
    let funcion = document.getElementById("funcionFilter").value;
    let competencia = document.getElementById("competenciaFilter").value;
    let semestre = document.getElementById("semestreFilter").value;

    let validRows = curriculumData.filter(function(row){{
        if(asignatura !== "ALL" && row.asignatura !== asignatura) return false;
        if(funcion !== "ALL" && row.funcion !== funcion) return false;
        if(competencia !== "ALL" && row.competencia !== competencia) return false;
        if(semestre !== "ALL" && row.semestre !== semestre) return false;
        return true;
    }});

    let activeAsignaturas = new Set();
    let activeCompetencias = new Set();

    validRows.forEach(function(row){{
        activeAsignaturas.add(row.asignatura);
        activeCompetencias.add(row.competencia);
    }});

    if(mode === "mode1"){{
        nodes.forEach(function(node){{
            let isVisible = false;
            if(node.tipo === "asignatura" && activeAsignaturas.has(node.id)){{
                isVisible = true;
            }} else if(node.tipo === "competencia" && activeCompetencias.has(node.id)){{
                isVisible = true;
            }}
            nodes.update({{ id: node.id, hidden: !isVisible }});
        }});

        edges.forEach(function(edge){{
            if(edge.modo === "mode1"){{
                let isVisible = activeAsignaturas.has(edge.from) && activeCompetencias.has(edge.to);
                edges.update({{ id: edge.id, hidden: !isVisible }});
            }} else {{
                edges.update({{ id: edge.id, hidden: true }});
            }}
        }});

    }} else if(mode === "mode2"){{
        nodes.forEach(function(node){{
            let isVisible = (node.tipo === "asignatura" && activeAsignaturas.has(node.id));
            nodes.update({{ id: node.id, hidden: !isVisible }});
        }});

        edges.forEach(function(edge){{
            if(edge.modo === "mode2"){{
                let isVisible = activeAsignaturas.has(edge.from) && activeAsignaturas.has(edge.to);
                edges.update({{ id: edge.id, hidden: !isVisible }});
            }} else {{
                edges.update({{ id: edge.id, hidden: true }});
            }}
        }});
    }}

    network.fit({{ animation: true }});
}}

// Ejecución inicial para aplicar estado tras renderizado del grafo
setTimeout(function(){{
    applyFilters();
}}, 500);
</script>
"""

with open(output_file, "r", encoding="utf-8") as f:
    html = f.read()

html = html.replace("<body>", f"<body>{selector_html}{legend_html}")
html = html.replace("</body>", js_code + "</body>")

with open(output_file, "w", encoding="utf-8") as f:
    f.write(html)

print("Visualizador v2 generado correctamente con soporte de selector de modos.")